{{- if and (.Values.defrag.config.auth.enabled) (not .Values.defrag.config.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "etcd-defrag.auth.secretName" . }}
data:
  etcd-password: {{ .Values.defrag.config.auth.password | default (randAlphaNum 32) | b64enc }}
{{- end }}
