{{- if and (.Values.persistence.enabled) (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  {{- if .Values.persistence.annotations }}
  annotations:
    {{- toYaml .Values.persistence.annotations | nindent 4 }}
  {{- end }}
  name: {{ include "headwind-mdm.fullname" . }}
  labels:
    {{- include "headwind-mdm.labels" . | nindent 4 }}
spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
