---
apiVersion: v2
name: prometheus-pve-exporter
description: A Helm chart for bootstrapping a PVE Exporter. Uses ServiceMonitor to collect metrics.
type: application
version: 1.0.5
appVersion: "2.2.4"
home: https://github.com/christianknell/helm-charts
icon: https://camo.githubusercontent.com/2df2ac41e1b8a1484be236c75e395981b31bfd670eff46b5c182ea0be9475310/68747470733a2f2f7777772e70726f786d6f782e636f6d2f696d616765732f70726f786d6f782f50726f786d6f785f73796d626f6c5f7374616e646172645f6865782e706e67
maintainers:
  - name: christianknell
    email: christian@knell.it
sources:
  - https://github.com/prometheus-pve/prometheus-pve-exporter
