# -- Provide a name in place of `prometheus-pve-exporter`
nameOverride: ""

# -- String to fully override `"prometheus-pve-exporter.fullname"`
fullnameOverride: ""

image:
  repository: prompve/prometheus-pve-exporter
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# -- If defined, uses a Secret to pull an image from a private Docker registry or repository.
imagePullSecrets: []

# optional arguments to disable collectors of the exporter. By default all collectors are enabled.
args: []
  # - "--no-collector.status"
  # - "--no-collector.version"
  # - "--no-collector.node"
  # - "--no-collector.cluster"
  # - "--no-collector.resources"
  # - "--no-collector.config"

env:
  # define how to authenticate against pve instances: password, token
  pveAuthType: "token"
  pveUser: ""
  pvePassword: ""
  pveTokenName: ""
  pveTokenValue: ""
  # if you provide an existing secret, no additional secret will be created. Depending on the setting in pveAuthType the secret needs to have password OR tokenName and tokenValue fields.
  pveExistingSecretName: ""
  # Optional: set to false to skip SSL/TLS verification
  pveVerifySsl: false

serviceMonitor:
   # -- Enable a prometheus ServiceMonitor
  enabled: false
  # -- Prometheus ServiceMonitor labels
  additionalLabels: {}
    # release: prometheus
  # -- Prometheus ServiceMonitor selector
  selector: {}
    # prometheus: kube-prometheus
  # -- Prometheus ServiceMonitor interval
  interval: 30s
  # -- Prometheus ServiceMonitor namespace
  namespace: ""
  # -- Prometheus [MetricRelabelConfigs] to apply to samples before ingestion
  metricRelabelings: []
  # -- Prometheus [RelabelConfigs] to apply to samples before scraping
  relabelings: []
    # - source_labels: [__address__]
    #   target_label: __param_target
    # - source_labels: [__param_target]
    #   target_label: instance
    # - target_label: __address__
    #   replacement: prometheus-pve-exporter:9221  # PVE exporter service.
  # -- Prometheus
  pveTargets: []

replicaCount: 1

# -- Annotations to be added to exporter pods
podAnnotations: {}

# -- container-level security context
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534

service:
  type: ClusterIP
  port: 80

# -- Resource limits and requests for the controller pods.
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- [Node selector]
nodeSelector: {}

# -- [Tolerations] for use with node taints
tolerations: []

# -- Assign custom [affinity] rules
affinity: {}

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
