apiVersion: v2
name: proxyweb
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "latest"
home: https://github.com/christianknell/helm-charts
sources:
  - https://github.com/edmodo/proxyweb/
deprecated: true
