apiVersion: v2
name: proxyweb
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: "latest"
home: https://github.com/christianknell/helm-charts
maintainers:
  - name: christianknell
    email: christian@knell.it
sources:
  - https://github.com/edmodo/proxyweb/
