apiVersion: v2
appVersion: postgresql-v1.39.5
description: Umami is a simple, fast, privacy-focused alternative to Google Analytics.
name: umami
type: application
version: 1.0.5
home: https://github.com/christianknell/helm-charts
icon: https://raw.githubusercontent.com/umami-software/umami/master/public/android-chrome-512x512.png
maintainers:
  - name: christianknell
    email: christian@knell.it
sources:
  - https://github.com/umami-software/umami
  - https://umami.is/
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.1.9
    condition: postgresql.enabled
  - name: mysql
    repository: https://charts.bitnami.com/bitnami
    version: 9.4.7
    condition: mysql.enabled
