{{- if .Values.configuration -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shlink-web.fullname" . }}
  labels:
    {{- include "shlink-web.labels" . | nindent 4 }}
data:
  servers.json: |
    {{ toJson .Values.configuration }}
{{- end }}
