apiVersion: v2
name: baserow
description: Baserow is an open source no-code database and Airtable alternative.
type: application
version: 1.0.3
appVersion: 1.13.3
home: https://github.com/christianknell/helm-charts
icon: https://baserow.io/img/favicon_192.png
maintainers:
  - name: christianknell
    email: christian@knell.it
sources:
  - https://gitlab.com/bramw/baserow
  - https://baserow.io
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.1.8
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.4.2
    condition: redis.enabled
