# -- Provide a name in place of `baserow`
nameOverride: ""

# -- String to fully override `"baserow.fullname"`
fullnameOverride: ""

frontend:

  image:
    # -- image repository
    repository: baserow/web-frontend
    # -- image pull policy
    pullPolicy: Always
    # -- Overrides the image tag
    tag: "1.13.3"

  # -- If defined, uses a Secret to pull an image from a private Docker registry or repository.
  imagePullSecrets: []

  # -- Annotations to be added to the frontend pods
  podAnnotations: {}

  # -- pod-level security context
  podSecurityContext: {}
    # fsGroup: 2000

  # -- Number of replicas
  replicaCount: 1

  # -- Resource limits and requests for the controller pods.
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # -- container-level security context
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  serviceAccount:
    # -- Specifies whether a service account should be created
    create: true
    # -- Annotations to add to the service account
    annotations: {}
    # -- The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  service:
    # -- Kubernetes service type
    type: ClusterIP
    # -- Kubernetes port where service is exposed
    port: 3000

  ingress:
    # -- Enable ingress record generation
    enabled: false
    # -- IngressClass that will be be used to implement the Ingress
    className: ""
    # -- Additional annotations for the Ingress resource
    annotations: {}
      # cert-manager.io/cluster-issuer: cluster-issuer-name
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    # -- An array with hosts and paths
    # @default -- see [values.yaml](./values.yaml)
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    # -- An array with the tls configuration
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  autoscaling:
    # -- Enable Horizontal POD autoscaling 
    enabled: false
    # -- Minimum number of replicas
    minReplicas: 1
    # -- Maximum number of replicas
    maxReplicas: 100
    # -- Target CPU utilization percentage
    targetCPUUtilizationPercentage: 80
    # -- Target Memory utilization percentage
    targetMemoryUtilizationPercentage: 80

  # -- Node labels for pod assignment
  nodeSelector: {}

  # -- Toleration labels for pod assignment
  tolerations: []

  # -- Affinity settings for pod assignment
  affinity: {}

  # -- additional environment variables to be added to the pods
  extraEnv: []

  # -- see https://baserow.io/docs/installation%2Fconfiguration
  config:
    # -- A list of file paths to Nuxt module.js files to load as additional Nuxt modules into Baserow on startup.
    additionalModules: ""
    # -- When opening the Baserow login page a check is run to ensure the PUBLIC_BACKEND_URL/BASEROW_PUBLIC_URL variables are set correctly and your browser can correctly connect to the backend. If misconfigured an error is shown. If you wish to disable this check and warning set this to any non empty value.
    disablePublicUrlCheck: ""
    # -- Set to `true` or `1` to disable Google docs file preview.
    disableGoogleDocsFilePreview: ""
    # -- Set to `1` to force download links to download files via XHR query to bypass `Content-Disposition: inline` that can’t be overridden in another way. If your files are stored under another origin, you also must add CORS headers to your server.
    downloadFileViaXhr: "0"
    # -- Controls how many application snapshots can be created per group.
    maxSnapshotsPerGroup: "-1"

backend:

  asgi:

    image:
      # -- image repository
      repository: baserow/backend
      # -- image pull policy
      pullPolicy: Always
      # -- Overrides the image tag
      tag: "1.13.3"

    # -- If defined, uses a Secret to pull an image from a private Docker registry or repository.
    imagePullSecrets: []

    # -- Annotations to be added to the frontend pods
    podAnnotations: {}

    # -- pod-level security context
    podSecurityContext: {}
      # fsGroup: 2000

    # -- Number of replicas
    replicaCount: 1

    # -- Resource limits and requests for the controller pods.
    resources: {}
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi

    # -- container-level security context
    securityContext: {}
      # capabilities:
      #   drop:
      #   - ALL
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000

    serviceAccount:
      # -- Specifies whether a service account should be created
      create: true
      # -- Annotations to add to the service account
      annotations: {}
      # -- The name of the service account to use.
      # If not set and create is true, a name is generated using the fullname template
      name: ""

    service:
      # -- Kubernetes service type
      type: ClusterIP
      # -- Kubernetes port where service is exposed
      port: 8000

    ingress:
      # -- Enable ingress record generation for the backend
      enabled: false
      # -- IngressClass that will be be used to implement the Ingress
      className: ""
      # -- Additional annotations for the Ingress resource
      annotations: {}
        # cert-manager.io/cluster-issuer: cluster-issuer-name
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
      # -- An array with hosts and paths
      # @default -- see [values.yaml](./values.yaml)
      hosts:
        - host: chart-example.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      # -- An array with the tls configuration
      tls: []
      #  - secretName: chart-example-tls
      #    hosts:
      #      - chart-example.local

    autoscaling:
      # -- Enable Horizontal POD autoscaling 
      enabled: false
      # -- Minimum number of replicas
      minReplicas: 1
      # -- Maximum number of replicas
      maxReplicas: 100
      # -- Target CPU utilization percentage
      targetCPUUtilizationPercentage: 80
      # -- Target Memory utilization percentage
      targetMemoryUtilizationPercentage: 80

    # -- Node labels for pod assignment
    nodeSelector: {}

    # -- Toleration labels for pod assignment
    tolerations: []

    # -- Affinity settings for pod assignment
    affinity: {}

    # -- additional environment variables to be added to the pods
    extraEnv: []

  wsgi:

    image:
      # -- image repository
      repository: baserow/backend
      # -- image pull policy
      pullPolicy: Always
      # -- Overrides the image tag
      tag: "1.13.3"

    # -- If defined, uses a Secret to pull an image from a private Docker registry or repository.
    imagePullSecrets: []

    # -- Annotations to be added to the frontend pods
    podAnnotations: {}

    # -- pod-level security context
    podSecurityContext: {}
      # fsGroup: 2000

    # -- Number of replicas
    replicaCount: 1

    # -- Resource limits and requests for the controller pods.
    resources: {}
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi

    # -- container-level security context
    securityContext: {}
      # capabilities:
      #   drop:
      #   - ALL
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000

    serviceAccount:
      # -- Specifies whether a service account should be created
      create: true
      # -- Annotations to add to the service account
      annotations: {}
      # -- The name of the service account to use.
      # If not set and create is true, a name is generated using the fullname template
      name: ""

    service:
      # -- Kubernetes service type
      type: ClusterIP
      # -- Kubernetes port where service is exposed
      port: 8000

    ingress:
      # -- Enable ingress record generation for the backend
      enabled: false
      # -- IngressClass that will be be used to implement the Ingress
      className: ""
      # -- Additional annotations for the Ingress resource
      annotations: {}
        # cert-manager.io/cluster-issuer: cluster-issuer-name
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
      # -- An array with hosts and paths
      # @default -- see [values.yaml](./values.yaml)
      hosts:
        - host: chart-example.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      # -- An array with the tls configuration
      tls: []
      #  - secretName: chart-example-tls
      #    hosts:
      #      - chart-example.local

    autoscaling:
      # -- Enable Horizontal POD autoscaling 
      enabled: false
      # -- Minimum number of replicas
      minReplicas: 1
      # -- Maximum number of replicas
      maxReplicas: 100
      # -- Target CPU utilization percentage
      targetCPUUtilizationPercentage: 80
      # -- Target Memory utilization percentage
      targetMemoryUtilizationPercentage: 80

    # -- Node labels for pod assignment
    nodeSelector: {}

    # -- Toleration labels for pod assignment
    tolerations: []

    # -- Affinity settings for pod assignment
    affinity: {}

    # -- additional environment variables to be added to the pods
    extraEnv: []

ingress:
  # -- Enable ingress record generation
  enabled: true
  # -- IngressClass that will be be used to implement the Ingress
  className: ""
  # -- Additional annotations for the Ingress resource
  annotations: {}
    # cert-manager.io/cluster-issuer: cluster-issuer-name
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- An array with hosts and paths
  # @default -- see [values.yaml](./values.yaml)
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  # -- An array with the tls configuration
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

postgresql:
  enabled: false

redis:
  enabled: false
