apiVersion: v2
name: etcd-defrag
description: A Helm chart for running a defragmentation CronJob for ETCD
type: application
version: 1.0.0
appVersion: 3.5.6
home: https://github.com/christianknell/helm-charts
icon: https://cdn.worldvectorlogo.com/logos/etcd-1.svg
maintainers:
  - name: christianknell
    email: christian@knell.it
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/etcd
  - https://etcd.io
