apiVersion: v2
name: netcupscp-exporter
description: Prometheus Exporter for Netcup Server Control Panel (SCP)
type: application
version: 1.0.0
appVersion: "v0.1.3"
home: https://github.com/christianknell/helm-charts
icon: https://pbs.twimg.com/profile_images/1148537659637358593/rlfCvTK5_400x400.png
maintainers:
  - name: christianknell
    email: christian@knell.it
sources:
  - https://github.com/mrueg/netcupscp-exporter
