apiVersion: v2
description: A Helm chart to deploy workload to gain direct access to the host of the Kubernetes cluster
name: node-access
type: application
version: 1.0.0
appVersion: 1.36.0
home: https://github.com/christianknell/helm-charts
icon: https://raw.githubusercontent.com/kubernetes/community/master/icons/png/infrastructure_components/labeled/node-256.png
maintainers:
  - name: christianknell
    email: christian@knell.it
