# configuration for the chart-testing tool: https://github.com/helm/chart-testing
remote: origin
target-branch: main
lint-conf: .github/config/yamllint.yaml
chart-yaml-schema: .github/config/chart-schema.yaml
validate-maintainers: false
validate-chart-schema: true
validate-yaml: true
check-version-increment: true
chart-dirs:
  - charts
helm-extra-args: --timeout 300
upgrade: true
skip-missing-values: true
release-label: release
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
release-notes-file: CHANGELOG.md
