# Explanation: Add the label 'ci-cd' to a PR if any file within the '.github' folder is changed
ci-cd: .github/*
cusdis: charts/cusdis/*
ipmi-exporter: charts/ipmi-exporter/*
ipsec-exporter: charts/ipsec-exporter/*
isso: charts/isso/*
kube-ops-view: charts/kube-ops-view/*
kutt: charts/kutt/*
netcup-scp-exporter: charts/netcup-scp-exporter/*
openvas: charts/openvas/*
passbolt-ha: charts/passbolt-ha/*
polr: charts/polr/*
popeye: charts/popeye/*
prometheus-pve-exporter: charts/prometheus-pve-exporter/*
proxysql: charts/proxysql/*
proxyweb: charts/proxyweb/*
shlink-backend: charts/shlink-backend/*
shlink-web: charts/shlink-web/*
skooner: charts/skooner/*
talkyard: charts/talkyard/*
typo3: charts/typo3/*
