{{- $fullName := include "popeye.fullname" . -}}
{{- $serviceName := include "popeye.serviceAccountName" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $fullName }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ $fullName }}
  apiGroup: rbac.authorization.k8s.io
