{{- if and (.Values.cronJob.prometheus.basicAuth.enabled) (not .Values.cronJob.prometheus.basicAuth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "popeye.prometheus.secretName" . }}
data:
  pushgateway-password: {{ .Values.cronJob.prometheus.basicAuth.password | b64enc }}
{{- end }}
