{{- if .Values.kubedoom.namespace }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubedoom.fullname" . }}
  namespace: {{ .Values.kubedoom.namespace | quote }}
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs: ["get", "list", "delete"]
{{- end }}
