{{- if and (not .Values.syncserver.config.existingSecret) .Values.syncserver.config.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "syncserver.secretName" . }}
data:
  syncserver-secret: {{ .Values.syncserver.config.secret | b64enc }}
{{- end }}
