{{- if not .Values.env.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netcupscp-exporter.fullname" . }}
data:
  SCP_LOGINNAME: {{ .Values.env.loginName |b64enc }}
  SCP_PASSWORD: {{ .Values.env.password | b64enc }}
{{- end }}
