{{- if .Values.celery.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "baserow.celery.serviceAccountName" . }}
  labels:
    {{- include "baserow.celery.labels" . | nindent 4 }}
  {{- with .Values.celery.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
