apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "baserow.frontend.fullname" . }}
  labels:
    {{- include "baserow.frontend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "baserow.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "baserow.frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.frontend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "baserow.frontend.serviceAccountName" . }}
      {{- with .Values.frontend.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "baserow.frontend.name" . }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          args:
            - nuxt
          env:
            # Baserow Settings
            {{- if .Values.frontend.config.additionalModules }}
            - name: ADDITIONAL_MODULES
              value: {{ .Values.frontend.config.additionalModules | quote }}
            {{- end }}
            {{- if .Values.frontend.config.disablePublicUrlCheck }}
            - name: BASEROW_DISABLE_PUBLIC_URL_CHECK
              value: {{ .Values.frontend.config.disablePublicUrlCheck | quote }}
            {{- end }}
            {{- if .Values.frontend.config.disableGoogleDocsFilePreview }}
            - name: BASEROW_DISABLE_GOOGLE_DOCS_FILE_PREVIEW
              value: {{ .Values.frontend.config.disableGoogleDocsFilePreview | quote }}
            {{- end }}
            {{- if .Values.frontend.config.maxSnapshotsPerGroup }}
            - name: BASEROW_MAX_SNAPSHOTS_PER_GROUP
              value: {{ .Values.frontend.config.maxSnapshotsPerGroup | quote }}
            {{- end }}
            - name: DOWNLOAD_FILE_VIA_XHR
              value: {{ .Values.frontend.config.downloadFileViaXhr | quote }}
            {{- range .Values.frontend.extraEnv }}
            {{- if and (.name) (.value) }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /_health
              port: {{ .Values.frontend.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /_health
              port: {{ .Values.frontend.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
          {{- with .Values.frontend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
