{{- if .Values.psp.enabled }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  labels:
    {{- include "proxyweb.labels" . | nindent 4 }}
  name: {{ include "proxyweb.fullname" . }}
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - 'secret'
  {{- if .Values.config }}
  - 'configMap'
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "proxyweb.labels" . | nindent 4 }}
  name: {{ include "proxyweb.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ include "proxyweb.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "proxyweb.labels" . | nindent 4 }}
  name: {{ include "proxyweb.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "proxyweb.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "proxyweb.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
