{{- if .Values.configuration.config }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxyweb.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  config.yml: |
    {{- .Values.configuration.config | toYaml | b64enc | nindent 4 }}
{{- end }}
