apiVersion: v2
name: skooner
description: Simple Kubernetes real-time dashboard and management.
type: application
version: 0.0.3
appVersion: "stable"
home: https://github.com/christianknell/helm-charts
icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu8eQrFBosk7yHTiDEwjnVcMRyDD5uIaNXhlZ1m0yiC4H8RP1j0PlBPtgtv0bdH0JwlOE
maintainers:
  - name: christianknell
    email: christian@knell.it
sources:
  - https://github.com/skooner-k8s/skooner
