apiVersion: v1
kind: Service
metadata:
  name: {{ include "maildev.fullname" . }}-http
  labels:
    {{- include "maildev.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.http.type }}
  ports:
    - port: {{ .Values.services.http.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "maildev.selectorLabels" . | nindent 4 }}
