apiVersion: v2
name: shlink-backend
description: A PHP-based self-hosted URL shortener that can be used to serve shortened URLs under your own domain.
type: application
version: 1.1.7
appVersion: "3.3.2"
home: https://github.com/christianknell/helm-charts
icon: https://shlink.io/images/shlink-logo-blue.svg
maintainers:
  - name: christianknell
    email: christian@knell.it
sources:
  - https://github.com/shlinkio/shlink
  - https://shlink.io
dependencies:
  - name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 11.4.1
    condition: mariadb.enabled
  - name: mysql
    repository: https://charts.bitnami.com/bitnami
    version: 9.4.5
    condition: mysql.enabled
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.1.3
    condition: postgresql.enabled
  - name: rabbitmq
    repository: https://charts.bitnami.com/bitnami
    version: 11.1.5
    condition: rabbitmq.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.3.14
    condition: redis.enabled
