apiVersion: v2
name: kutt
description: Kutt is a free modern URL shortener.
type: application
version: 1.8.4
appVersion: "v2.7.4"
home: https://github.com/christianknell/helm-charts
icon: https://www.saashub.com/images/app/service_logos/15/d634f2359578/large.png
maintainers:
  - name: christianknell
    email: christian@knell.it
sources:
  - https://github.com/thedevs-network/kutt
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.2.6
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.9.2
    condition: redis.enabled
annotations:
  artifacthub.io/screenshots: |
    - title: Simply shorten your link using the Web UI.
      url: https://noted.lol/content/images/size/w1000/2022/08/kutt-self-hosted-url-shortener-generate-unauthorized.png
    - title: Advanced options for shortening a link.
      url: https://noted.lol/content/images/2022/08/kutt-self-hosted-url-shortener-generate.png
    - title: You can see a list of the most recent created links and some statistical data about them.
      url: https://noted.lol/content/images/size/w1000/2022/08/kutt-self-hosted-url-shortener-recent-links.png
    - title: View detailed statistics about each created link.
      url: https://kutt.it/images/callout.png
