name: Lint and Test Charts

on:
  pull_request:
    branches: [main]
    paths: [charts/**]

jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3

  lint:
    needs:
      - pre-commit
    runs-on: ubuntu-20.04
    container: ghcr.io/chgl/kube-powertools:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check if documentation is up-to-date
        run: generate-docs.sh && git diff --exit-code HEAD
      - name: Update dependencies
        run: find charts/ ! -path charts/ -maxdepth 1 -type d -exec helm dependency update {} \;
      - name: Run YAML lint
        run: yamllint .
      - name: Run Powerlint
        run: chart-powerlint.sh
      # used to test whether the changelog generation process works properly
      - name: Generate changelogs
        run: bash .github/generate-chart-changelogs.sh
