name: "Kyverno Policy Checks"

on:
  pull_request:
    branches: [main]
    paths: ["charts/**"]
  push:
    branches: [main]
    paths: ["charts/**"]
  workflow_dispatch:

env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }}

jobs:

  list-charts:
    runs-on: ubuntu-latest
    outputs:
      charts: "${{ steps.list-charts.outputs.chartsJson }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: List charts
        id: list-charts
        run: |
          charts=$(ls charts/ | xargs -I {} echo "charts/"{}" " | tr -d '\n')
          arr=(`echo $charts`)
          json=$(echo "${arr[@]}" | jq -ncR 'inputs | split(" ")')
          echo "chartsJson=$json" >> $GITHUB_OUTPUT

  kyverno-validate:
    runs-on: ubuntu-latest
    needs: [list-charts]
    strategy:
      fail-fast: false
      matrix:
        chart:
          - ${{ fromJson(needs.list-charts.outputs.charts) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout kyverno-policies
        uses: actions/checkout@v2
        with:
          repository: kyverno/policies
          ref: main

      - name: Install Helm
        uses: azure/setup-helm@v1

      - name: List files
        run: |
          pwd
          ls -al .

      - name: Test against Kyverno policies
        uses: ckotzbauer/kyverno-test-action@v2
        with:
          chart-dir: "${{ matrix.chart }}"
          policy-files: |
            best-practices/require_probes/require_probes.yaml
            best-practices/disallow-empty-ingress-host/disallow_empty_ingress_host.yaml
            best-practices/require_drop_all/require_drop_all.yaml
