name: Chart-Preparation

on:
  pull_request:
    branches: [main]
    paths: ["charts/**"]
  push:
    branches: [main]
    paths: ["charts/**"]
  workflow_dispatch:

jobs:

  readme:
    runs-on: ubuntu-latest
    container: ghcr.io/chgl/kube-powertools:latest
    steps:
      - name: checkout git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check if documentation is up-to-date
        run: generate-docs.sh && git diff --exit-code HEAD
      - name: Update dependencies
        run: find charts/ ! -path charts/ -maxdepth 1 -type d -exec helm dependency update {} \;
      - name: Generate changelogs
        run: generate-chart-changelogs.sh
      - name: Check readme
        shell: bash
        run: |
          set -euo pipefail
          docker run --rm --volume "$(pwd):/helm-docs" -u "$(id -u)" jnorwood/helm-docs:latest
          if ! git diff --exit-code
          then
            echo "Documentation not up to date. Please run helm-docs and commit changes!" >&2
            exit 1
          fi
