name: Chart-Preparation

on:
  workflow_run:
    workflows: ["Chart-Testing"]
    branches: [main]
    types: [completed]

jobs:

  readme:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    container: ghcr.io/chgl/kube-powertools:latest
    steps:
      - name: checkout git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check if documentation is up-to-date
        run: generate-docs.sh && git diff --exit-code HEAD
      - name: Update dependencies
        run: find charts/ ! -path charts/ -maxdepth 1 -type d -exec helm dependency update {} \;
      - name: Generate changelogs
        run: generate-chart-changelogs.sh
      - name: Check readme
        shell: bash
        run: |
          set -euo pipefail
          docker run --rm --volume "$(pwd):/helm-docs" -u "$(id -u)" jnorwood/helm-docs:latest
          if ! git diff --exit-code
          then
            echo "Documentation not up to date. Please run helm-docs and commit changes!" >&2
            exit 1
          fi
