name: Release Helm Charts

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Chart-Testing"]
    branches: [main]
    types: [completed]

jobs:
  release2github:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: 3.*

      - name: Add Helm repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
      - name: Update dependencies
        run: find charts/ ! -path charts/ -maxdepth 1 -type d -exec helm dependency update {} \;

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          
  release2chartmuseum:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: 3.*
      
      - name: Add Helm repository
        run: helm repo add christianknell https://charts.knell.it
        
      - name: Push current version to Helm repository
        run: |
          cd charts/
          foreach i ( * )
            echo "Working on $i folder ..."
          end

#      - uses: goodsmileduck/helm-push-action@v3
#        env:
#          CHART_FOLDER: 'charts/'
#          FORCE: 'false'
#          CHARTMUSEUM_URL: 'https://charts.knell.it'
#          CHARTMUSEUM_USER: '${{ secrets.CHARTMUSEUM_USER }}'
#          CHARTMUSEUM_PASSWORD: '${{ secrets.CHARTMUSEUM_PASSWORD }}'
