{{- if and (not .Values.umami.hash.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "umami.hash.secretName" . }}
data:
  {{- if .Values.umami.hash.salt }}
  hash-salt: {{ .Values.umami.hash.salt | b64enc }}
  {{- else }}
  hash-salt: {{ randAlphaNum 50 | b64enc }}
  {{- end }}
{{- end }}
